### ISSUE TITLE
Time.gbm_bn does not work in Astropy 6.0

### ISSUE THREAD

**Issue by AdamGoldstein-USRA** [USRA-STI/gdt-fermi#21]
Example:

```python
from gdt.missions.fermi.time import Time
Time.now().gbm_bn
``` 
Results in the error

> AttributeError: 'GbmBurstNumber' object has no attribute 'mask_if_needed'

This appears to be due to a change in Astropy 6.0.  I have verified this works in Astropy 5.2.2.

**Comment by BillCleveland-USRA** [comment]
The deprecated function was removed on Apr 4, 2024 and was part of the merge to master for the v2.1.0 release.
